---
abstract: 'Command-line utility to validate JSON using JSON Schema'
author:
  - 'Andre Santos <andrefs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-jsonschema
requires:
  Data::Dump: 0
  JSON: 0
  JSON::Schema: 0
  Moo: 0
  autodie: 0
  feature: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/andrefs/App-jsonschema/issues
  homepage: https://github.com/andrefs/App-jsonschema
  repository: git://github.com/andrefs/App-jsonschema.git
version: 0.03
